#!/bin/bash
#
# Todo: seperate different functionality to seperate scripts


if [ "$(id -u)" != "0" ]; then
        echo "You must run this command as root"
        exit 1
fi

NEWUSERNAME=$1
APACHEGROUP=http
EXPECTED_ARGS=1
GENERALERROR=1
E_BADARGS=65
HTMLROOT=/home/$NEWUSERNAME/public_html
PROJECTSROOT=/home/tomkarho/Projects/

if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user" 2>&1
  exit $GENERALERROR
fi

if [ $# -ne $EXPECTED_ARGS ]; then
	echo "Usage: $0 projectname"
	exit $E_BADARGS
fi


if id -u $NEWUSERNAME >/dev/null 2>&1; then
    echo "user $NEWUSERNAME already exists"
else 	
	echo "Creating user $NEWUSERNAME"   
	useradd -m -g users -G git,$APACHEGROUP -s /bin/bash $NEWUSERNAME
fi


if [ -d "$HTMLROOT" ]; then
	echo "Directory $HTMLROOT alrady exists"
else
	echo "Creating html root"
	mkdir $HTMLROOT
fi


if [ -f "$HTMLROOT/index.html" ]; then
	echo "Index file already exists"
else
	echo "Creating index file"
	echo $NEWUSERNAME > $HTMLROOT/index.html
fi


echo "Changing folder and file permissions"
chown -R $NEWUSERNAME:$APACHEGROUP $HTMLROOT
chmod o+x $HTMLROOT/../
chmod o+x $HTMLROOT
chmod 755 $HTMLROOT
chmod 644 $HTMLROOT/index.html

echo "Initializing git repositry"

if [ -d "$PROJECTSROOT/$NEWUSERNAME" ]; then
	echo "Git repository already exists"
else
	git init $PROJECTSROOT/$NEWUSERNAME
fi
